//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Timer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PC_Timer_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PC_Timer_lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC_Timer.Languages.PC_Timer_lang", typeof(PC_Timer_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string btn_later {
            get {
                return ResourceManager.GetString("btn_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timer.
        /// </summary>
        public static string btn_start {
            get {
                return ResourceManager.GetString("btn_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop timer.
        /// </summary>
        public static string btn_stop {
            get {
                return ResourceManager.GetString("btn_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Monitor active.
        /// </summary>
        public static string checkbox_display {
            get {
                return ResourceManager.GetString("checkbox_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Standby.
        /// </summary>
        public static string checkbox_sleep {
            get {
                return ResourceManager.GetString("checkbox_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea, initial work.
        /// </summary>
        public static string contrubitor_hundhausen {
            get {
                return ResourceManager.GetString("contrubitor_hundhausen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Design.
        /// </summary>
        public static string contrubitor_yasujizr {
            get {
                return ResourceManager.GetString("contrubitor_yasujizr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who worked on the project and what they did:.
        /// </summary>
        public static string contrubitors_info_text {
            get {
                return ResourceManager.GetString("contrubitors_info_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout user.
        /// </summary>
        public static string dropdown_logout {
            get {
                return ResourceManager.GetString("dropdown_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string dropdown_restart {
            get {
                return ResourceManager.GetString("dropdown_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string dropdown_shutdown {
            get {
                return ResourceManager.GetString("dropdown_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybernate.
        /// </summary>
        public static string dropdown_suspend {
            get {
                return ResourceManager.GetString("dropdown_suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string label_hour {
            get {
                return ResourceManager.GetString("label_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string label_min {
            get {
                return ResourceManager.GetString("label_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string label_sec {
            get {
                return ResourceManager.GetString("label_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrubitors.
        /// </summary>
        public static string lable_contrubitors {
            get {
                return ResourceManager.GetString("lable_contrubitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit issues:.
        /// </summary>
        public static string lable_issues {
            get {
                return ResourceManager.GetString("lable_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External libraries.
        /// </summary>
        public static string lable_libraries {
            get {
                return ResourceManager.GetString("lable_libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string lable_license {
            get {
                return ResourceManager.GetString("lable_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string lable_version {
            get {
                return ResourceManager.GetString("lable_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website:.
        /// </summary>
        public static string lable_website {
            get {
                return ResourceManager.GetString("lable_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcecode.
        /// </summary>
        public static string menu_code {
            get {
                return ResourceManager.GetString("menu_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string menu_de {
            get {
                return ResourceManager.GetString("menu_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string menu_en {
            get {
                return ResourceManager.GetString("menu_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string menu_error {
            get {
                return ResourceManager.GetString("menu_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string menu_info {
            get {
                return ResourceManager.GetString("menu_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string menu_lang {
            get {
                return ResourceManager.GetString("menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer stopped.
        /// </summary>
        public static string msgbox_abort_head {
            get {
                return ResourceManager.GetString("msgbox_abort_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got stopped.
        /// </summary>
        public static string msgbox_abort_txt {
            get {
                return ResourceManager.GetString("msgbox_abort_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set time is very low. Do you want to start the Timer anyway?.
        /// </summary>
        public static string msgbox_ask_start {
            get {
                return ResourceManager.GetString("msgbox_ask_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds until execution.
        /// </summary>
        public static string msgbox_ask_time {
            get {
                return ResourceManager.GetString("msgbox_ask_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got not started because the date is set to a past date.
        /// </summary>
        public static string msgbox_dateoutofrange_txt {
            get {
                return ResourceManager.GetString("msgbox_dateoutofrange_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Timer got not started.
        /// </summary>
        public static string msgbox_fail_head {
            get {
                return ResourceManager.GetString("msgbox_fail_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got not started because of an unknown error.
        /// </summary>
        public static string msgbox_fail_txt {
            get {
                return ResourceManager.GetString("msgbox_fail_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the Program to see the changes.
        /// </summary>
        public static string msgbox_lang_changed {
            get {
                return ResourceManager.GetString("msgbox_lang_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        public static string msgbox_lang_changed_title {
            get {
                return ResourceManager.GetString("msgbox_lang_changed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got not started because only numbers are allowed.
        /// </summary>
        public static string msgbox_noint_txt {
            get {
                return ResourceManager.GetString("msgbox_noint_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got started.
        /// </summary>
        public static string msgbox_start_head {
            get {
                return ResourceManager.GetString("msgbox_start_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got started. The user will got logged out as planed.
        /// </summary>
        public static string msgbox_start_logout_txt {
            get {
                return ResourceManager.GetString("msgbox_start_logout_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got started. The PC will restart as planed.
        /// </summary>
        public static string msgbox_start_restart_txt {
            get {
                return ResourceManager.GetString("msgbox_start_restart_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got started. The PC will shutdown as planed.
        /// </summary>
        public static string msgbox_start_shutodown_txt {
            get {
                return ResourceManager.GetString("msgbox_start_shutodown_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer got started. The PC will hybernate as planed.
        /// </summary>
        public static string msgbox_start_suspend_txt {
            get {
                return ResourceManager.GetString("msgbox_start_suspend_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load License File..
        /// </summary>
        public static string rtf_failed_load {
            get {
                return ResourceManager.GetString("rtf_failed_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string tab_date {
            get {
                return ResourceManager.GetString("tab_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string tab_time {
            get {
                return ResourceManager.GetString("tab_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor only can be set active, when the PC is not allowed to go into standby.
        /// </summary>
        public static string tooltip_displayonlywhen {
            get {
                return ResourceManager.GetString("tooltip_displayonlywhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string updater_day {
            get {
                return ResourceManager.GetString("updater_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string updater_days {
            get {
                return ResourceManager.GetString("updater_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and start Setup.
        /// </summary>
        public static string updater_download {
            get {
                return ResourceManager.GetString("updater_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look every.
        /// </summary>
        public static string updater_interval {
            get {
                return ResourceManager.GetString("updater_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me in {0} days again.
        /// </summary>
        public static string updater_later {
            get {
                return ResourceManager.GetString("updater_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to check for updates automatically?.
        /// </summary>
        public static string updater_message {
            get {
                return ResourceManager.GetString("updater_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string updater_never {
            get {
                return ResourceManager.GetString("updater_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is avaible
        ///How do you wan&apos;t to procede?.
        /// </summary>
        public static string updater_newversion {
            get {
                return ResourceManager.GetString("updater_newversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version avaible.
        /// </summary>
        public static string updater_newversion_Title {
            get {
                return ResourceManager.GetString("updater_newversion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Releases?.
        /// </summary>
        public static string updater_prereleases {
            get {
                return ResourceManager.GetString("updater_prereleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for Updates?.
        /// </summary>
        public static string updater_title {
            get {
                return ResourceManager.GetString("updater_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string updater_visit {
            get {
                return ResourceManager.GetString("updater_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PC-Timer.
        /// </summary>
        public static string window_about {
            get {
                return ResourceManager.GetString("window_about", resourceCulture);
            }
        }
    }
}
